export const DATA_UPCOMING = [
  {
    id: 1,
    title: "드라큘라 1차 티켓 오픈",
    // musical_id: 34,
    // date: "2021-11-11",
    ticketing_time: "11:00 AM",
    ticketing_site: ["인터파크", "멜론티켓", "티켓링크"],
    alarmDeposit_isOn: true,
    alarmCancel_isOn: false,
  },
  {
    id: 2,
    title: "그날들 1차 티켓 오픈",
    musical_id: 34,
    date: "2021-11-11",
    ticketing_time: "2:00 AM",
    ticketing_site: ["인터파크", "멜론티켓", "티켓링크"],
    alarmDeposit_isOn: true,
    alarmCancel_isOn: false,
  },
  {
    id: 3,
    title: "그날들 1차 티켓 오픈",
    musical_id: 34,
    date: "2021-11-11",
    ticketing_time: "2:00 AM",
    ticketing_site: ["인터파크", "멜론티켓", "티켓링크"],
    alarmDeposit_isOn: true,
    alarmCancel_isOn: false,
  },
  {
    id: 4,
    title: "그날들 1차 티켓 오픈",
    musical_id: 34,
    date: "2021-11-11",
    ticketing_time: "2:00 AM",
    ticketing_site: ["인터파크", "멜론티켓", "티켓링크"],
    alarmDeposit_isOn: true,
    alarmCancel_isOn: false,
  },
  {
    id: 5,
    title: "그날들 1차 티켓 오픈",
    musical_id: 34,
    date: "2021-11-11",
    ticketing_time: "2:00 AM",
    ticketing_site: ["인터파크", "멜론티켓", "티켓링크"],
    alarmDeposit_isOn: true,
    alarmCancel_isOn: false,
  },
];
